### ISSUE TITLE
Extensions containing SQL commands?

### ISSUE THREAD

**Issue by edent** [FreshRSS/Extensions#106]
Can extensions contain mySQL commands?

I'd like to turn this - https://github.com/FreshRSS/FreshRSS/issues/1771#issuecomment-633869281 - into a extension which always sorts the main feed by the declared date.

**Comment by Alkarex** [comment]
Yes, extensions may contain SQL command, remembering that FreshRSS supports SQLite, PostgreSQL, MySQL / MariaDB.
While doing it once at start is fine (after you are done installing FreshRSS / importing many feeds), be aware that I do not advise constantly re-ordering the DB by declared date, as several other things might break such as background updates, paging, APIs (depending on where the sorting is done), etc. So please take some time to understand the current behaviour first. From the same issue, please see e.g. https://github.com/FreshRSS/FreshRSS/issues/1771#issuecomment-359195655 
What could easily be done is to show the retrieved date in FreshRSS's main view instead of the declared date (an approach used by several other related systems).
In the future, we may natively support showing articles with different sort orders in the main view, but that requires a bit more work.
