### ISSUE TITLE
xExtension-ImageProxy and FreshRSS 1.7.0

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/Extensions#16]
@Frenzie https://github.com/FreshRSS/FreshRSS/issues/1548#issuecomment-304350170

At a quick glance, the current extension is declared as "system" https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/metadata.json#L7 but seems to be using a user-specific configuration https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/extension.php#L8

**Comment by Frenzie** [comment]
Oh, I kind of forgot about https://github.com/FreshRSS/FreshRSS/issues/1257 where it was still unclear to me whether to fully switch to system or to go back to user. In my local version I had a full change to system but as I already pointed out there that's unrelated in the sense that it only affects being able a custom proxy URL. Changing the type back to user does allow me to enable/disable but as enable/disable is executed by FreshRSS and not the extension that should be otherwise unrelated.
