### ISSUE TITLE
xExtension-ColorfulList not working when only viewing unread messages

### ISSUE THREAD

**Issue by MarcelVersteeg** [FreshRSS/Extensions#183]
When I view the unread messages in FreshRSS and have the ColorfulList extension enabled, the messages are not colored, like they are when viewing all messages.

**Comment by Alkarex** [comment]
Ping @shinemoon

**Comment by shinemoon** [comment]
@MarcelVersteeg it sounds weird, while ColorfulList supposes to 'colorize' each '.flux_header' despites of read or unread view and actually I double checked and tried also in my side by switch between 'read/unread' view there... it works. 

So is it possible you can inspect the ul item in browser to see if the item like below , i.e. background style well applied in your side: 

`<ul class="horizontal-list flux_header websitefull" style="background: rgba(62, 9, 19, 0.07);">`

**Comment by MarcelVersteeg** [comment]
Hi @shinemoon 

The matter seems to be a little more complicated, but let me first answer your question about the theme: I'm using Alternative Dark.

When I opened my FreshRSS this morning and immediately went to the "Unread" messages (by clicking this button: 
![image](https://github.com/FreshRSS/Extensions/assets/72593247/35be2944-5d74-4923-93f4-6dc636c87e2f)
), the list was colored as it was when the complete list was shown.

Then I execeuted the following steps:

1. At the bottom of the list, click "Mark all as read" (this returned me to the complete list of all messages and they were correctly colored)
2. Marked some messages as "Unread" (by clicking the envelope in front of the message)
3. Open the "Unread" messages again (this shows the list of the messages marked as "Unread", but there is no coloring).

In that situation I also checked to see if the style was applied to the item and it wasn't.

As a side question: what colors are being used for the origins? Can I configure that somewhere?

**Comment by shinemoon** [comment]
Hi, @MarcelVersteeg ,

Thanks, I tried the procedure you addressed, yes, it can be reproduced in my side, and this kind of issue is caused by when you operate like that, the colorization action is not triggered (which I use the DOM childlist change as trigger for the color generation..).

Now I have one [pull request](https://github.com/FreshRSS/Extensions/pull/186) to fix it.  Let's see.

And for your question: "As a side question: what colors are being used for the origins? Can I configure that somewhere?"

It's quite lazy method I am taking, i.e. just using the 'feed name' to generate random color => 'customized color' is not supported...after I consider the effort to be invested vs. the benefit it can bring (and also lazy me..)

Thanks,

**Comment by Alkarex** [comment]
@MarcelVersteeg please try the updated version by @shinemoon
