### ISSUE TITLE
Invidious Extension forked and updated

### ISSUE THREAD

**Issue by tunbridgep** [FreshRSS/Extensions#190]
Hi, I have made a more up-to-date version of the Invidious extension, forked from the cn-tools version which was in turn forked from Korbeks version.

You can see it here:

https://github.com/tunbridgep/freshrss-invidious

Would this be worthwhile replacing the one in the readme?

**Comment by Alkarex** [comment]
Hello,
Looks good, but when possible, I would like to encourage fixes to be made by pull requests instead of forks, and even if the parent is not responsive, I think it is a good etiquette to send a PR.
Ping @cn-tools for @Korbak for potential merge and/or giving each-other the possibility to contribute to the same repository.

**Comment by Alkarex** [comment]
Readme updated in https://github.com/FreshRSS/Extensions/pull/192

**Comment by tunbridgep** [comment]
I did try getting in touch with them beforehand, I got no response.

Thanks for completing this.
